[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "essentials-configuration"
version = "2.0.0"
authors = [{ name = "Roberto Prevato", email = "roberto.prevato@gmail.com" }]
description = "Implementation of key-value pair based configuration for Python applications."
